architecture-beta
  group app(folder)[App]
  group devtools(folder)[Dev Tools]
  group supabase(cloud)[Supabase]
  group telemetry(database)[Telemetry]
  service otel(server)[OTEL Collector] in telemetry
  service frontend(app)[Frontend] in app
  service backend(server)[Backend] in app
  service edgefn(server)[Edge Functions] in supabase
  service db(database)[Database] in supabase
  service logs(database)[Logs] in telemetry
  service telemetrytools(server)[Telemetry Tools] in telemetry
  frontend:R -- L:backend
  backend:R -- L:edgefn
  edgefn:R -- L:db
  db:R -- L:logs
  logs:R -- L:otel
  otel:R -- L:telemetrytools
  telemetrytools:R -- L:backend

