---
accTitle: Pipeline
accDescr: TODO: Add description for Pipeline
domain: dev-tools
type: flowchart
title: Pipeline
index: ../../../mmd-shared/config/index.md
---



flowchart LR
  Start --> Step1 --> Step2 --> End
