---
accTitle: Diagram Index
accDescr: TODO: Add description for Diagram Index
domain: dev-tools
type: graph
title: Diagram Index
index: ../../../mmd-shared/config/index.md
---






graph LR
  Index[Diagram Index] --> A[Control Plane]
  Index --> B[Pipeline]
