# Cloud Build configuration for ProspectPro deployment
# Fixes service account logging requirements

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/rmpcgab-prospectpro-us-central1-alextorelli-prospectpro--majuv/prospectpro:$COMMIT_SHA',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/rmpcgab-prospectpro-us-central1-alextorelli-prospectpro--majuv/prospectpro:latest',
      '.'
    ]

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '--all-tags',
      'us-central1-docker.pkg.dev/$PROJECT_ID/rmpcgab-prospectpro-us-central1-alextorelli-prospectpro--majuv/prospectpro'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'prospectpro'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/rmpcgab-prospectpro-us-central1-alextorelli-prospectpro--majuv/prospectpro:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3100'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production,PORT=3100,ALLOW_DEGRADED_START=true'

# CRITICAL: Logging configuration required when using custom service account
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100

# Timeout for the entire build (20 minutes)
timeout: '1200s'