# Cloud Build Configuration for ProspectPro v3.1
# Native Google Cloud deployment with Supabase Vault integration

steps:
  # Step 1: Create Artifact Registry repository if needed
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe prospectpro --location=us-central1 &>/dev/null; then
          echo "🏗️ Creating Artifact Registry repository..."
          gcloud artifacts repositories create prospectpro \
            --location=us-central1 \
            --repository-format=docker \
            --description="ProspectPro container repository"
          echo "✅ Repository created successfully"
        else
          echo "✅ Repository already exists"
        fi
    id: 'setup-registry'

  # Step 2: Build Docker container
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/prospectpro/app:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/prospectpro/app:latest'
      - '.'
    id: 'build-container'
    waitFor: ['setup-registry']

  # Step 3: Push container to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/prospectpro/app'
    id: 'push-container'
    waitFor: ['build-container']

  # Step 4: Deploy to Cloud Run with environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'prospectpro'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/prospectpro/app:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--concurrency=100'
      - '--timeout=300'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-env-vars=ALLOW_DEGRADED_START=true'
      - '--set-env-vars=SUPABASE_URL=${_SUPABASE_URL}'
      - '--set-env-vars=SUPABASE_SECRET_KEY=${_SUPABASE_SECRET_KEY}'
      - '--set-env-vars=WEBHOOK_AUTH_TOKEN=${_WEBHOOK_AUTH_TOKEN}'
      - '--service-account=prospectpro-deployment@leadgen-471822.iam.gserviceaccount.com'
    id: 'deploy-cloud-run'
    waitFor: ['push-container']

  # Step 5: Get service URL and test health
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get the deployed service URL
        SERVICE_URL=$(gcloud run services describe prospectpro --region=us-central1 --format='value(status.url)')
        echo "🌐 Service deployed at: $SERVICE_URL"
        
        # Wait for service to be ready
        echo "⏳ Waiting for service to be ready..."
        sleep 30
        
        # Test health endpoint
        echo "🧪 Testing health endpoint..."
        curl -f --max-time 30 --retry 5 --retry-delay 10 "$SERVICE_URL/health" || echo "❌ Health check failed but deployment succeeded"
        
        # Test basic API endpoint
        echo "🧪 Testing business discovery API..."
        curl -X POST --max-time 30 -H "Content-Type: application/json" \
          -d '{"businessType":"restaurant","location":"Austin, TX","maxResults":1}' \
          -f "$SERVICE_URL/api/business/discover-businesses" || echo "❌ API test failed but deployment succeeded"
        
        echo "✅ Deployment completed - Service URL: $SERVICE_URL"
    id: 'health-check'
    waitFor: ['deploy-cloud-run']

# Substitution variables (set in Cloud Build trigger)
substitutions:
  _SUPABASE_URL: ''
  _SUPABASE_SECRET_KEY: ''
  _WEBHOOK_AUTH_TOKEN: ''

# Build configuration optimized for production
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  substitutionOption: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY

# Build timeout (20 minutes for comprehensive build and test)
timeout: '1200s'