version: '3.8'

services:
  prospectpro-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"    # Backend API
      - "5173:5173"    # Frontend dev server (Vite)
      - "9229:9229"    # Node.js debugging port
    environment:
      - NODE_ENV=development
      - DEBUG=prospectpro:*
      - HOST=0.0.0.0
      - PORT=3000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
      - FOURSQUARE_API_KEY=${FOURSQUARE_API_KEY}
      - FOURSQUARE_SERVICE_API_KEY=${FOURSQUARE_SERVICE_API_KEY}
      - HUNTER_IO_API_KEY=${HUNTER_IO_API_KEY}
      - APOLLO_API_KEY=${APOLLO_API_KEY}
      - NEVERBOUNCE_API_KEY=${NEVERBOUNCE_API_KEY}
      - ZEROBOUNCE_API_KEY=${ZEROBOUNCE_API_KEY}
      - PERSONAL_ACCESS_TOKEN=${PERSONAL_ACCESS_TOKEN}
      - ALLOW_DEGRADED_START=true
    volumes:
      # Live code reloading - mount source code
      - .:/app
      - /app/node_modules  # Preserve node_modules from container
      - /app/.git          # Preserve git history
      # Persistent development data
      - dev_logs:/app/logs
      - dev_data:/app/data
      - dev_uploads:/app/uploads
    stdin_open: true  # Keep STDIN open for interactive debugging
    tty: true         # Allocate pseudo-TTY for better logging
    restart: unless-stopped
    networks:
      - prospectpro-dev-network

  # Frontend development server (if needed separately)
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5174:5173"  # Alternative port to avoid conflicts
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - VITE_EDGE_FUNCTIONS_URL=${SUPABASE_URL}/functions/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - prospectpro-dev
    networks:
      - prospectpro-dev-network
    profiles:
      - with-frontend

  # Optional: Development database for local testing
  postgres-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: prospectpro_dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - dev_postgres:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d:ro
    networks:
      - prospectpro-dev-network
    profiles:
      - with-local-db

volumes:
  dev_logs:
  dev_data:
  dev_uploads:
  dev_postgres:

networks:
  prospectpro-dev-network:
    driver: bridge