# ProspectPro Railway Configuration
# Production-ready deployment with Supabase Transaction Pooler integration

[build]
builder = "NIXPACKS"
buildCommand = "npm ci --only=production"
watchPaths = ["server.js", "modules/**", "api/**", "public/**", "package.json"]

[deploy]
# Health check configuration for zero-downtime deployments
healthcheckPath = "/health"
healthcheckTimeout = 90
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

# Production start command with optimized settings
startCommand = "node server.js"

# Sleep configuration for cost optimization  
sleepApplication = false  # Keep alive for production monitoring
staticUrl = true         # Enable static URL for consistent monitoring

# Environment variables (Railway will inject from project settings)
[environment]
NODE_ENV = "production"
# PORT is automatically provided by Railway - do not override

# Supabase Configuration Notes:
# Set these in Railway's Environment Variables UI:
# SUPABASE_URL = "https://your-project-ref.supabase.co"  
# SUPABASE_SECRET_KEY = "sb_secret_your_actual_key_here"
# GOOGLE_PLACES_API_KEY = "your_google_api_key"
# PERSONAL_ACCESS_TOKEN = "your_admin_token"