# ProspectPro Railway Configuration
# Production-ready deployment with comprehensive monitoring and debugging

[build]
builder = "NIXPACKS"
buildCommand = "npm ci --only=production"
watchPaths = ["server-enhanced.js", "modules/**", "api/**", "public/**", "database/**", "package.json"]

[deploy]
# Health check configuration for zero-downtime deployments
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1

# Enhanced start command with comprehensive monitoring
startCommand = "node server-enhanced.js"

# Monitoring and debugging configuration
sleepApplication = false  # Keep alive for production monitoring
staticUrl = true         # Enable static URL for consistent monitoring

# Environment variables with debugging support
[environment]
NODE_ENV = "production"
ALLOW_DEGRADED_START = "true"  # Allow startup even with some failures
LOG_LEVEL = "info"             # Enhanced logging for debugging
NODE_OPTIONS = "--max-old-space-size=1024"  # Memory optimization

# Build optimization for Railway
[build.env]
NPM_CONFIG_PRODUCTION = "false"  # Allow dev dependencies during build for debugging tools

# Additional monitoring endpoints available:
# - /health: Basic health check (used by Railway)
# - /diag: Comprehensive diagnostics
# - /boot-report: Boot sequence analysis  
# - /system-info: Full system information
# - /metrics: Prometheus metrics

# Required Environment Variables (set in Railway dashboard):
# SUPABASE_URL = "https://your-project-ref.supabase.co"  
# SUPABASE_SECRET_KEY = "sb_secret_your_actual_key_here"
# GOOGLE_PLACES_API_KEY = "your_google_api_key"
# PERSONAL_ACCESS_TOKEN = "your_admin_token"