#!/bin/bash
echo "🏗️ Generating test production .env configuration..."

# Create .env file with production configuration  
cat > .env << ENVEOF
# ================================
# PRODUCTION ENVIRONMENT CONFIGURATION
# Generated by GitHub Actions on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Commit: test-commit-hash
# Branch: main
# ================================

# Environment Settings
NODE_ENV=production
PORT=3000
ALLOW_DEGRADED_START=false

# Supabase Database Connection (from GitHub Secrets)
SUPABASE_URL=https://test.supabase.co
SUPABASE_SECRET_KEY=test_secret_key

# Production Performance Settings
DAILY_BUDGET_LIMIT=100.00
DEFAULT_BUDGET_LIMIT=25.00
PER_LEAD_COST_LIMIT=2.00
COST_ALERT_THRESHOLD=80.00

MIN_CONFIDENCE_SCORE=85
PRE_VALIDATION_THRESHOLD=75
EXPORT_CONFIDENCE_THRESHOLD=90

REQUEST_TIMEOUT=30000
REQUEST_DELAY=500
MAX_CONCURRENT_REQUESTS=10
BATCH_SIZE=25
CACHE_TTL_SECONDS=3600

GOOGLE_PLACES_RPM=1000
HUNTER_IO_RPM=100
NEVERBOUNCE_RPM=300
RATE_LIMIT_WINDOW=60000

# Production Features (All Enabled)
ENABLE_PROMETHEUS_METRICS=true
ENABLE_PERFORMANCE_LOGGING=true
ENABLE_COST_TRACKING=true
ENABLE_ERROR_REPORTING=true
LOG_LEVEL=info

ENABLE_TTL_CACHE=true
ENABLE_BATCH_PROCESSING=true
ENABLE_SMART_ROUTING=true
ENABLE_CIRCUIT_BREAKER=true

ENABLE_REQUEST_VALIDATION=true
ENABLE_RATE_LIMITING=true
REQUIRE_API_AUTHENTICATION=true

ENABLE_DATABASE_CONNECTION_POOLING=true
ENABLE_GRACEFUL_SHUTDOWN=true
ENABLE_HEALTH_CHECKS=true

# Deployment Settings
BIND_ADDRESS=0.0.0.0
GRACEFUL_SHUTDOWN_TIMEOUT=30000
HEALTH_CHECK_INTERVAL=30000
DATABASE_CONNECTION_TIMEOUT=5000
API_CLIENT_TIMEOUT=15000
WEBHOOK_TIMEOUT=10000

# Build Information
BUILD_TIMESTAMP=$(date -u +"%Y-%m-%d_%H-%M-%S_UTC")
BUILD_COMMIT=test-commit-hash
BUILD_BRANCH=main
BUILD_ACTOR=test-actor
ENVEOF

echo "✅ Production .env file generated successfully"
echo "📄 File size: $(wc -c < .env) bytes"
echo "📋 Configuration lines: $(wc -l < .env) lines"

# Test file existence and content
if [ -f .env ]; then
  echo "✅ .env file exists and is readable"
  echo "📁 First 5 lines:"
  head -5 .env
else
  echo "❌ .env file was not created"
  exit 1
fi
