%%{init: {\'theme\': \'dark\'}}%%
%%{init: {'theme': 'dark'}}%%
stateDiagram-v2
    [*] --> DEV_MCP
    [*] --> TROUBLE_MCP
    [*] --> PROD_MCP

    state DEV_MCP {
        state Secondary_DEV    
            Supabase_DEV --> IntegrationHub_DEV
            IntegrationHub_DEV --> Observability_DEV
        }

    state TROUBLE_MCP {
        state Secondary_TROUBLE 
            Supabase_TROUBLE --> IntegrationHub_TROUBLE
            IntegrationHub_TROUBLE --> Observability_TROUBLE
        }

    state PROD_MCP {
        state Secondary_PROD 
            IntegrationHub_PROD --> Observability_PROD
        }
