---
accTitle: Deployment Pipeline
accDescr: TODO: Add description for Deployment Pipeline
domain: integration
type: sequenceDiagram
title: Deployment Pipeline
index: ../../../../mmd-shared/config/index.md
---

sequenceDiagram
  Dev->>CI: Push
  CI->>CD: Build
  CD->>Prod: Deploy
