---
accTitle: Data Ingestion
accDescr: TODO: Add description for Data Ingestion
domain: integration
type: flowchart
title: Data Ingestion
index: ../../../mmd-shared/config/index.md
---






flowchart TD
  Source --> ETL --> Warehouse
