app = "prospectpro"
primary_region = "ams" # Change to your preferred region

[build]
  dockerfile = "docker/Dockerfile.production"

[env]
  NODE_ENV = "production"
  SUPABASE_URL = "your_supabase_url"
  SUPABASE_SECRET_KEY = "your_supabase_secret_key"
  # Add other environment variables as needed

[deploy]
  release_command = "npm run migrate" # Command to run after deployment

[[services]]
  http_service = "app"
  internal_port = 3000
  processes = "app"

[services.app]
  # Optional: Configure scaling
  instances = 1
  cpu = "shared"
  memory = "512mb"

  [[services.app.ports]]
    port = "80"
    handlers = ["http"]

  [[services.app.ports]]
    port = "443"
    handlers = ["tls", "http"]