service: web
name: prospectpro
env: node
buildCommand: npm install
startCommand: npm start
envVars:
  NODE_ENV: production
  SUPABASE_SECRET_KEY: ${SUPABASE_SECRET_KEY}
  SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
  SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
  SUPABASE_PUBLISHABLE_KEY: ${SUPABASE_PUBLISHABLE_KEY}
  PERSONAL_ACCESS_TOKEN: ${PERSONAL_ACCESS_TOKEN}
  ALLOW_DEGRADED_START: true
  PORT: 3000
autoDeploy: true
region: oregon
plan: starter