version: "3"

tasks:
  unit:
    desc: Run business-discovery unit tests
    cmds:
      - npx vitest run unit/ --config ../../configs/vitest.agents.config.ts

  integration:
    desc: Run business-discovery integration tests
    cmds:
      - npx vitest run integration/ --config ../../configs/vitest.agents.config.ts

  e2e:
    desc: Run business-discovery E2E tests
    cmds:
      - npx playwright test e2e/ --config ../../configs/playwright.agents.config.ts

  test:all:
    desc: Run all business-discovery tests
    cmds:
      - task: unit
      - task: integration
      - task: e2e

  debug:unit:
    desc: Debug unit tests with VS Code
    cmds:
      - npx vitest --inspect-brk unit/ --config ../../configs/vitest.agents.config.ts

  debug:e2e:
    desc: Debug E2E tests with headed browser
    cmds:
      - npx playwright test e2e/ --config ../../configs/playwright.agents.config.ts --headed --debug
