---
accTitle: Data Pipeline Flowchart
accDescr: TODO: Add description for Data Pipeline Flowchart
domain: dev-tools
type: flowchart
title: Data Pipeline Flowchart
index: ../../../mmd-shared/config/index.md
---




flowchart TD
  A[Source] --> B[Transform]
  B --> C[Sink]
