graph LR
  Index[Diagram Index] --> A[Control Plane]
  Index --> B[Pipeline]
graph LR
  %% index: ../../../../tooling/end-state/index.md %%
  Index[Diagram Index] --> A[Control Plane]
  Index --> B[Pipeline]
