version: '3.8'

# Docker Compose with GitHub Secrets Integration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.secrets.yml up -d

services:
  prospectpro:
    environment:
      # Core Database (from GitHub Secrets)
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY}
      
      # API Keys (from GitHub Secrets)
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
      - FOURSQUARE_API_KEY=${FOURSQUARE_API_KEY}
      - HUNTER_IO_API_KEY=${HUNTER_IO_API_KEY}
      - NEVERBOUNCE_API_KEY=${NEVERBOUNCE_API_KEY}
      - PERSONAL_ACCESS_TOKEN=${PERSONAL_ACCESS_TOKEN}
      
      # Application Settings
      - NODE_ENV=production
      - PORT=3000
      - ALLOW_DEGRADED_START=true

# To use this:
# 1. Set secrets in GitHub: Settings → Secrets and variables → Actions
# 2. Export secrets locally: export SUPABASE_URL="your_url_here"  
# 3. Run: docker-compose -f docker-compose.yml -f docker-compose.secrets.yml up -d