global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:16686"]

  - job_name: "prospectpro-mcp-servers"
    static_configs:
      - targets: ["host.docker.internal:3001"] # Adjust port as needed
    scrape_interval: 30s

  - job_name: "prospectpro-edge-functions"
    static_configs:
      - targets: ["host.docker.internal:54321"] # Supabase local port
    scrape_interval: 30s
