version: "3"

vars:
  VITEST_CONFIG: ./configs/vitest.agents.config.ts
  PLAYWRIGHT_CONFIG: ./configs/playwright.agents.config.ts
  REPORTS_DIR: ./reports

includes:
  business-discovery:
    taskfile: ./agents/business-discovery/Taskfile.yml
    dir: ./agents/business-discovery
  enrichment-orchestrator:
    taskfile: ./agents/enrichment-orchestrator/Taskfile.yml
    dir: ./agents/enrichment-orchestrator
  export-diagnostics:
    taskfile: ./agents/export-diagnostics/Taskfile.yml
    dir: ./agents/export-diagnostics

tasks:
  agents:test:unit:
    desc: Run all agent unit tests
    cmds:
      - npx vitest run --config {{.VITEST_CONFIG}}

  agents:test:integration:
    desc: Run all agent integration tests
    cmds:
      - npx vitest run --config {{.VITEST_CONFIG}} --testNamePattern="integration"

  agents:test:e2e:
    desc: Run all agent E2E tests (Playwright)
    cmds:
      - npx playwright test --config {{.PLAYWRIGHT_CONFIG}}

  agents:test:full:
    desc: Run complete test suite with linting
    deps:
      - lint
    cmds:
      - task: agents:test:unit
      - task: agents:test:e2e

  lint:
    desc: Run ESLint on test files
    cmds:
      - npx eslint "**/*.test.ts" "**/*.spec.ts" --max-warnings 0

  reports:clean:
    desc: Clean all test reports
    cmds:
      - rm -rf {{.REPORTS_DIR}}/*
      - echo "✓ Reports cleaned"

  reports:open:
    desc: Open Playwright HTML report
    cmds:
      - npx playwright show-report {{.REPORTS_DIR}}/playwright
