version: "3"
vars:
  VITEST_CONFIG: ./configs/vitest.agents.config.ts
  PLAYWRIGHT_CONFIG: ./configs/playwright.agents.config.ts
  REPORTS_DIR: ./reports

tasks:
  agents:test:unit:
    desc: Run all agent unit tests (Vitest)
    cmds:
      - npx vitest --config {{.VITEST_CONFIG}} run agents/unit
    sources:
      - agents/**/unit/**/*.test.ts
    generates:
      - "{{.REPORTS_DIR}}/coverage/*"

  agents:test:integration:
    desc: Run all agent integration tests (Vitest)
    cmds:
      - npx vitest --config {{.VITEST_CONFIG}} run agents/integration
    sources:
      - agents/**/integration/**/*.test.ts
    generates:
      - "{{.REPORTS_DIR}}/coverage/*"

  agents:test:e2e:
    desc: Run all agent E2E tests (Playwright)
    cmds:
      - npx playwright test --config {{.PLAYWRIGHT_CONFIG}}
    sources:
      - agents/**/e2e/**/*.spec.ts
    generates:
      - "{{.REPORTS_DIR}}/playwright/*"

  agents:test:full:
    desc: Run all agent tests (unit, integration, E2E)
    deps:
      - agents:test:unit
      - agents:test:integration
      - agents:test:e2e

  agents:test:watch:
    desc: Watch all agent unit/integration tests (Vitest)
    cmds:
      - npx vitest --config {{.VITEST_CONFIG}} watch

  agents:test:coverage:
    desc: Generate coverage report for all agent tests
    cmds:
      - npx vitest --config {{.VITEST_CONFIG}} run --coverage
    generates:
      - "{{.REPORTS_DIR}}/coverage/*"

  agents:test:lint:
    desc: Lint all agent test code
    cmds:
      - npx eslint agents/**/*.ts
    sources:
      - agents/**/*.ts

  agents:test:clean:
    desc: Clean all agent test reports
    cmds:
      - rm -rf {{.REPORTS_DIR}}/*
    generates:
      - "{{.REPORTS_DIR}}/*"

  reports:open:
    desc: Open Playwright HTML report
    cmds:
      - npx playwright show-report {{.REPORTS_DIR}}/playwright
# Per-agent Taskfiles should be placed in dev-tools/testing/agents/<agent>/Taskfile.yml
# Example agent Taskfile:
# version: '3'
# tasks:
#   unit:
#     desc: Run unit tests for this agent
#     cmds:
#       - npx vitest run --dir unit
#   e2e:
#     desc: Run E2E tests for this agent
#     cmds:
#       - npx playwright test --dir e2e
#     cmds:
