---
accTitle: Control Plane
accDescr: TODO: Add description for Control Plane
domain: dev-tools
type: graph
title: Control Plane
index: ../../../../mmd-shared/config/index.md
---

graph TD;
  A[Control Plane] --> B[Subsystem 1];
  A --> C[Subsystem 2];
