---
accTitle: Alerting Mesh
accDescr: TODO: Add description for Alerting Mesh
domain: integration
type: graph
title: Alerting Mesh
index: ../../../../mmd-shared/config/index.md
---

graph TD
  Monitor --> Alert1
  Monitor --> Alert2
