---
accTitle: Example Integration
accDescr: TODO: Add description for Example Integration
domain: integration
type: graph
title: Example Integration
index: ../../mmd-shared/config/index.md
---






graph TD; A-->B; B-->C; C-->A;
