export const BUSINESS_CATEGORIES = [
  "Automotive Services",
  "Education & Training",
  "Entertainment & Recreation",
  "Financial Services",
  "Food & Dining",
  "Government & Public Services",
  "Healthcare & Medical",
  "Home & Property Services",
  "Hospitality & Lodging",
  "Personal Care & Beauty",
  "Professional Services",
  "Religious & Community",
  "Retail & Shopping",
  "Technology & IT Services",
  "Transportation & Transit",
] as const;

export const BUSINESS_TYPES_BY_CATEGORY: Record<string, string[]> = {
  "Automotive Services": [
    "Auto Body Shop",
    "Auto Detailing",
    "Auto Parts Store",
    "Automotive Glass Service",
    "Car Dealer",
    "Car Rental",
    "Car Repair",
    "Car Wash",
    "Electric Vehicle Charging Station",
    "Gas Station",
    "Motorcycle Dealer",
    "Oil Change Service",
    "Rv Dealer",
    "Smog Check Station",
    "Tire Shop",
    "Towing Service",
    "Transmission Shop",
    "Truck Dealer",
  ],
  "Education & Training": [
    "Art School",
    "Charter School",
    "College",
    "Community College",
    "Cooking School",
    "Dance Studio",
    "Daycare",
    "Driving School",
    "Kindergarten",
    "Language School",
    "Library",
    "Music School",
    "Preschool",
    "Primary School",
    "Private School",
    "Public School",
    "School",
    "Secondary School",
    "Summer Camp Organizer",
    "Technical School",
    "Training Center",
    "Tutoring Center",
    "University",
    "Vocational School",
  ],
  "Entertainment & Recreation": [
    "Amusement Park",
    "Aquarium",
    "Arcade",
    "Arena",
    "Art Gallery",
    "Banquet Hall",
    "Beach",
    "Botanical Garden",
    "Bowling Alley",
    "Casino",
    "Comedy Club",
    "Concert Hall",
    "Convention Center",
    "Escape Room",
    "Event Venue",
    "Fitness Center",
    "Golf Course",
    "Gym",
    "Karaoke Venue",
    "Marina",
    "Mini Golf",
    "Movie Theater",
    "Museum",
    "Night Club",
    "Paintball",
    "Park",
    "Rock Climbing Gym",
    "Ski Resort",
    "Sports Complex",
    "Stadium",
    "Swimming Pool",
    "Tennis Court",
    "Theater",
    "Tourist Attraction",
    "Trampoline Park",
    "Wedding Venue",
    "Yoga Studio",
    "Zoo",
  ],
  "Financial Services": [
    "Atm",
    "Bank",
    "Check Cashing Service",
    "Credit Union",
    "Cryptocurrency Exchange",
    "Financial Planner",
    "Investment Firm",
    "Money Transfer Service",
    "Mortgage Broker",
    "Payday Lender",
    "Stock Broker",
  ],
  "Food & Dining": [
    "Bakery",
    "Bar",
    "Barbecue Restaurant",
    "Brewery",
    "Brunch Restaurant",
    "Buffet",
    "Burger Joint",
    "Cafe",
    "Catering Service",
    "Chinese Restaurant",
    "Cocktail Bar",
    "Coffee Shop",
    "Deli",
    "Dessert Shop",
    "Distillery",
    "Donut Shop",
    "Fast Food Restaurant",
    "Food Court",
    "Food Stand",
    "Food Truck",
    "Ice Cream Shop",
    "Indian Restaurant",
    "Italian Restaurant",
    "Japanese Restaurant",
    "Juice Bar",
    "Meal Delivery",
    "Meal Takeaway",
    "Mexican Restaurant",
    "Pizza Restaurant",
    "Pub",
    "Restaurant",
    "Sandwich Shop",
    "Seafood Restaurant",
    "Smoothie Shop",
    "Steakhouse",
    "Sushi Restaurant",
    "Taco Place",
    "Tea House",
    "Wine Bar",
    "Winery",
  ],
  "Government & Public Services": [
    "City Hall",
    "Consulate",
    "Courthouse",
    "County Office",
    "Dmv",
    "Embassy",
    "Fire Station",
    "Government Office",
    "Municipal Building",
    "Passport Office",
    "Police Station",
    "Post Office",
    "Public Library",
    "Public School",
    "Public Works",
    "Social Services Office",
    "Tax Office",
    "Voter Registration Office",
  ],
  "Healthcare & Medical": [
    "Acupuncture Clinic",
    "Chiropractor",
    "Dental Clinic",
    "Dentist",
    "Doctor",
    "Drugstore",
    "Health Insurance Office",
    "Hospital",
    "Medical Center",
    "Medical Equipment Supplier",
    "Medical Lab",
    "Mental Health Clinic",
    "Occupational Therapist",
    "Optical Clinic",
    "Optometrist",
    "Orthodontist",
    "Pharmacy",
    "Physical Therapy",
    "Physiotherapist",
    "Psychiatrist",
    "Psychologist",
    "Skin Care Clinic",
    "Speech Therapist",
    "Urgent Care",
    "Veterinary Care",
    "Wellness Center",
  ],
  "Home & Property Services": [
    "Appliance Repair",
    "Carpet Cleaning",
    "Cleaning Service",
    "Dry Cleaning",
    "Electrician",
    "Fence Contractor",
    "Flooring Contractor",
    "Gardener",
    "General Contractor",
    "Gutter Service",
    "Handyman",
    "Home Inspector",
    "Hvac Contractor",
    "Landscaping",
    "Laundry",
    "Locksmith",
    "Moving Company",
    "Painter",
    "Pest Control",
    "Plumber",
    "Pool Service",
    "Property Management",
    "Roofing Contractor",
    "Storage",
    "Window Cleaning",
  ],
  "Hospitality & Lodging": [
    "Bed And Breakfast",
    "Boutique Hotel",
    "Campground",
    "Extended Stay Hotel",
    "Guest House",
    "Hostel",
    "Hotel",
    "Inn",
    "Lodge",
    "Motel",
    "Resort",
    "Rv Park",
    "Vacation Rental",
  ],
  "Personal Care & Beauty": [
    "Barber Shop",
    "Beauty Salon",
    "Beautician",
    "Body Art Service",
    "Cosmetics Store",
    "Day Spa",
    "Eyebrow Threading",
    "Facial Spa",
    "Hair Care",
    "Hair Salon",
    "Makeup Artist",
    "Massage",
    "Nail Salon",
    "Piercing Shop",
    "Sauna",
    "Spa",
    "Tanning Studio",
    "Tattoo Parlor",
    "Waxing Salon",
  ],
  "Professional Services": [
    "Accounting",
    "Advertising Agency",
    "Architecture Firm",
    "Attorney",
    "Business Center",
    "Consultant",
    "Corporate Office",
    "Employment Agency",
    "Engineering Office",
    "Financial Advisor",
    "Insurance Agency",
    "Lawyer",
    "Marketing Agency",
    "Notary",
    "Real Estate Agency",
    "Recruiter",
    "Tax Preparation",
  ],
  "Religious & Community": [
    "Cemetery",
    "Church",
    "Civic Organization",
    "Community Center",
    "Crematorium",
    "Funeral Home",
    "Meditation Center",
    "Mosque",
    "Non-Profit Organization",
    "Place Of Worship",
    "Religious Center",
    "Social Club",
    "Spiritual Center",
    "Synagogue",
    "Temple",
  ],
  "Retail & Shopping": [
    "Antique Shop",
    "Art Supply Store",
    "Bicycle Store",
    "Book Store",
    "Boutique",
    "Clothing Store",
    "Convenience Store",
    "Craft Store",
    "Department Store",
    "Discount Store",
    "Dollar Store",
    "Electronics Store",
    "Florist",
    "Furniture Store",
    "Garden Center",
    "Gift Shop",
    "Grocery Store",
    "Hardware Store",
    "Hobby Shop",
    "Home Goods Store",
    "Jewelry Store",
    "Liquor Store",
    "Music Store",
    "Office Supply Store",
    "Optical Store",
    "Outlet Store",
    "Party Supply Store",
    "Pet Store",
    "Second Hand Store",
    "Shoe Store",
    "Shopping Mall",
    "Sporting Goods Store",
    "Supermarket",
    "Thrift Store",
    "Tobacco Shop",
    "Toy Store",
    "Vape Shop",
  ],
  "Technology & IT Services": [
    "App Development",
    "Cell Phone Store",
    "Co-Working Space",
    "Computer Repair",
    "Cybersecurity Firm",
    "Data Center",
    "Internet Cafe",
    "It Services",
    "Managed Services Provider",
    "Software Company",
    "Tech Support",
    "Telecommunications Service Provider",
    "Web Design",
  ],
  "Transportation & Transit": [
    "Airport",
    "Bike Rental",
    "Bus Station",
    "Bus Tour Agency",
    "Car Sharing",
    "Cruise Agency",
    "Ferry Terminal",
    "Limousine Service",
    "Parking Garage",
    "Parking Lot",
    "Rest Area",
    "Ride Share Location",
    "Scooter Rental",
    "Shuttle Service",
    "Subway Station",
    "Taxi Stand",
    "Train Station",
    "Travel Agency",
    "Truck Stop",
  ],
};
