version: "3"

vars:
  AGENT_DIR: ../../agents/mcp-servers
  TEST_CONFIG: ../configs/vitest.agents.config.ts
  PLAYWRIGHT_CONFIG: ../configs/playwright.agents.config.ts

tasks:
  unit:
    desc: Run MCP servers unit tests
    cmds:
      - npx vitest --config {{.TEST_CONFIG}} run {{.AGENT_DIR}}/unit
    sources:
      - "{{.AGENT_DIR}}/unit/**/*.test.ts"
      - "{{.AGENT_DIR}}/src/**/*.ts"
    generates:
      - "../reports/coverage/mcp-servers/*"

  integration:
    desc: Run MCP servers integration tests
    cmds:
      - npx vitest --config {{.TEST_CONFIG}} run {{.AGENT_DIR}}/integration
    sources:
      - "{{.AGENT_DIR}}/integration/**/*.test.ts"
      - "{{.AGENT_DIR}}/src/**/*.ts"
    generates:
      - "../reports/coverage/mcp-servers/*"

  e2e:
    desc: Run MCP servers E2E tests
    cmds:
      - npx playwright test --config {{.PLAYWRIGHT_CONFIG}} {{.AGENT_DIR}}/e2e
    sources:
      - "{{.AGENT_DIR}}/e2e/**/*.spec.ts"
      - "{{.AGENT_DIR}}/src/**/*.ts"
    generates:
      - "../reports/playwright/mcp-servers/*"

  test:
    desc: Run all MCP servers tests
    deps:
      - unit
      - integration
      - e2e

  watch:
    desc: Watch MCP servers unit/integration tests
    cmds:
      - npx vitest --config {{.TEST_CONFIG}} watch {{.AGENT_DIR}}

  coverage:
    desc: Generate coverage report for MCP servers
    cmds:
      - npx vitest --config {{.TEST_CONFIG}} run --coverage {{.AGENT_DIR}}
    generates:
      - "../reports/coverage/mcp-servers/*"

  lint:
    desc: Lint MCP servers code
    cmds:
      - npx eslint {{.AGENT_DIR}}/**/*.ts
    sources:
      - "{{.AGENT_DIR}}/**/*.ts"

  clean:
    desc: Clean MCP servers test reports
    cmds:
      - rm -rf ../reports/coverage/mcp-servers/*
      - rm -rf ../reports/playwright/mcp-servers/*
