---
accTitle: Boundary Checkpoints
accDescr: TODO: Add description for Boundary Checkpoints
domain: integration
type: flowchart
title: Boundary Checkpoints
index: ../../../mmd-shared/config/index.md
---



flowchart LR
  User -.-> Firewall -.-> App
