#!/bin/bash

# ProspectPro API Key Injection Script
# Injects API keys from Supabase Edge Function secrets into Vite environment variables

set -e

echo "🔑 ProspectPro API Key Injection"
echo "================================"

# Check if Supabase CLI is available
if ! command -v supabase &> /dev/null; then
    echo "❌ Supabase CLI not found. Please install: npm install -g supabase"
    exit 1
fi

# Check if we're linked to a Supabase project
if ! supabase status &> /dev/null; then
    echo "❌ Not linked to Supabase project. Run: supabase link --project-ref sriycekxdqnesdsgwiuc"
    exit 1
fi

echo "📡 Fetching API keys from Supabase Edge Function secrets..."

# Get the Google Maps API key from Supabase secrets
GOOGLE_MAPS_KEY=$(supabase secrets get GOOGLE_PLACES_API_KEY 2>/dev/null || echo "")

if [ -z "$GOOGLE_MAPS_KEY" ]; then
    echo "⚠️  Warning: GOOGLE_PLACES_API_KEY not found in Supabase secrets"
    echo "   Using empty value for development"
    GOOGLE_MAPS_KEY=""
else
    echo "✅ Retrieved Google Maps API key from Supabase secrets"
fi

# Update .env.local with injected API keys
cat > .env.local << EOF
# Vite Environment Variables for ProspectPro
# Generated by inject-api-keys.sh on $(date)

# Supabase Configuration
VITE_SUPABASE_URL=https://sriycekxdqnesdsgwiuc.supabase.co
VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyaXljZWt4ZHFuZXNkc2d3aXVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjU3ODksImV4cCI6MjA3MzU0MTc4OX0.Rx_1Hjz2eayKie0RpPB28i7_683ZwhVJ_5Eu_rzTWpI
VITE_EDGE_FUNCTIONS_URL=https://sriycekxdqnesdsgwiuc.supabase.co/functions/v1

# Google Maps API Configuration (injected from Supabase secrets)
VITE_GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_KEY
VITE_GOOGLE_PLACES_API_KEY=$GOOGLE_MAPS_KEY

# Note: Other API keys (Hunter.io, NeverBounce, etc.) are stored in
# Supabase Edge Function secrets and accessed only by Edge Functions
# They are NOT exposed to the frontend for security
EOF

echo "✅ API keys injected into .env.local"
echo "📁 Frontend now has access to:"
echo "   - Google Maps API key for map display"
echo "   - Supabase connection details"
echo ""
echo "🔒 Security Note: Sensitive API keys (Hunter.io, NeverBounce) remain"
echo "   secure in Supabase Edge Function secrets and are not exposed to frontend"
echo ""
echo "🚀 Ready to build and deploy!"