%%{init: {\'theme\': \'dark\'}}%%
%%{init: {'theme': 'dark'}}%%
stateDiagram-v2
    [*] --> EnvironmentDetection

    state EnvironmentDetection {
        [*] --> DetectContext
        DetectContext --> LocalDev : git branch = dev/*
        DetectContext --> SharedDev : git branch = develop
        DetectContext --> Testing : git branch = test/*
        DetectContext --> Staging : git branch = troubleshooting
        DetectContext --> Production : git branch = main
        DetectContext --> Incident : alert triggered
    }

    state LocalDev {
        [*] --> SelectDevCluster
        SelectDevCluster --> DevMCPCluster
        DevMCPCluster --> ActivateDebugMode
        ActivateDebugMode --> DebugMode[@debug]
        DebugMode --> UXParticipant[@ux]
        DebugMode --> PlatformParticipant[@platform]
    }

    state SharedDev {
        [*] --> SelectIntegrationCluster
        SelectIntegrationCluster --> IntegrationMCPCluster
        IntegrationMCPCluster --> ActivateFeatureMode
        ActivateFeatureMode --> FeatureMode[@feature]
        FeatureMode --> UXParticipantShared[@ux]
        FeatureMode --> IntegrationsParticipant[@integrations]
    }

    state Testing {
        [*] --> SelectTestingCluster
        SelectTestingCluster --> TestingMCPCluster
        TestingMCPCluster --> ActivateFeatureModeQA
        ActivateFeatureModeQA --> FeatureModeQA[@feature]
        FeatureModeQA --> UXParticipantQA[@ux]
        FeatureModeQA --> IntegrationsParticipantQA[@integrations]
    }

    state Staging {
        [*] --> SelectStagingCluster
        SelectStagingCluster --> StagingMCPCluster
        StagingMCPCluster --> ActivateSupportMode
        ActivateSupportMode --> SupportMode[@support]
        SupportMode --> PlatformParticipantStage[@platform]
        SupportMode --> SecOpsParticipantStage[@secops]
    }

    state Production {
        [*] --> SelectProductionCluster
        SelectProductionCluster --> ProductionMCPCluster
        ProductionMCPCluster --> ActivateOptimizeMode
        ActivateOptimizeMode --> OptimizeMode[@optimize]
        OptimizeMode --> DevOpsParticipantProd[@devops]
        OptimizeMode --> SecOpsParticipantProd[@secops]
    }

    state Incident {
        [*] --> SelectIncidentCluster
        SelectIncidentCluster --> IncidentMCPCluster
        IncidentMCPCluster --> ActivateSecurityMode
        ActivateSecurityMode --> SecurityMode[@security]
        SecurityMode --> SecOpsParticipantIncident[@secops]
        SecurityMode --> DevOpsParticipantIncident[@devops]
    }
