version: "3"

vars:
  AGENT_DIR: ../../agents/context
  TEST_CONFIG: ../configs/vitest.agents.config.ts
  PLAYWRIGHT_CONFIG: ../configs/playwright.agents.config.ts

tasks:
  unit:
    desc: Run context agent unit tests
    cmds:
      - npx vitest --config {{.TEST_CONFIG}} run {{.AGENT_DIR}}/unit
    sources:
      - "{{.AGENT_DIR}}/unit/**/*.test.ts"
      - "{{.AGENT_DIR}}/src/**/*.ts"
    generates:
      - "../reports/coverage/context/*"

  integration:
    desc: Run context agent integration tests
    cmds:
      - npx vitest --config {{.TEST_CONFIG}} run {{.AGENT_DIR}}/integration
    sources:
      - "{{.AGENT_DIR}}/integration/**/*.test.ts"
      - "{{.AGENT_DIR}}/src/**/*.ts"
    generates:
      - "../reports/coverage/context/*"

  e2e:
    desc: Run context agent E2E tests
    cmds:
      - npx playwright test --config {{.PLAYWRIGHT_CONFIG}} {{.AGENT_DIR}}/e2e
    sources:
      - "{{.AGENT_DIR}}/e2e/**/*.spec.ts"
      - "{{.AGENT_DIR}}/src/**/*.ts"
    generates:
      - "../reports/playwright/context/*"

  test:
    desc: Run all context agent tests
    deps:
      - unit
      - integration
      - e2e

  watch:
    desc: Watch context agent unit/integration tests
    cmds:
      - npx vitest --config {{.TEST_CONFIG}} watch {{.AGENT_DIR}}

  coverage:
    desc: Generate coverage report for context agent
    cmds:
      - npx vitest --config {{.TEST_CONFIG}} run --coverage {{.AGENT_DIR}}
    generates:
      - "../reports/coverage/context/*"

  lint:
    desc: Lint context agent code
    cmds:
      - npx eslint {{.AGENT_DIR}}/**/*.ts
    sources:
      - "{{.AGENT_DIR}}/**/*.ts"

  clean:
    desc: Clean context agent test reports
    cmds:
      - rm -rf ../reports/coverage/context/*
      - rm -rf ../reports/playwright/context/*
