name: ProspectPro CI/CD

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint --if-present

      - name: Run data validation tests
        run: |
          if [ -f "test/test-real-data.js" ]; then
            node test/test-real-data.js
          fi

      - name: Run syntax checks
        run: |
          node -c server.js
          find modules/ -name "*.js" -exec node -c {} \;
          find api/ -name "*.js" -exec node -c {} \;

      - name: Check for fake data patterns
        run: |
          # Fail if fake data patterns are found
          if grep -r "fake\|dummy\|placeholder" --include="*.js" modules/ api/ | grep -v "test\|spec"; then
            echo "❌ Fake data patterns detected in production code"
            exit 1
          fi
          echo "✅ No fake data patterns found"

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run security audit
        run: |
          npm audit --audit-level=moderate

      - name: Check environment variables
        run: |
          if [ -f ".env" ]; then
            echo "⚠️ .env file found in repository - this should be gitignored"
            exit 1
          fi
          echo "✅ No .env file in repository"

  deploy:
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Railway
        run: |
          echo "🚀 Railway deployment triggered automatically"
          echo "Visit Railway dashboard for deployment status"
