---
accTitle: Supabase Stack
accDescr: TODO: Add description for Supabase Stack
domain: integration
type: flowchart
title: Supabase Stack
index: ../../../mmd-shared/config/index.md
---



flowchart TD
  User --> Supabase
  Supabase --> DB
